### ISSUE TITLE
 Elixirfm.User.get_recent_tracks: api version not passed correctly

### ISSUE THREAD

**Issue by msp** [jrichocean/Elixirfm#1]
Hi

FYI - out of the box, this did not work for me so I had to make the request manually, setting the api_version as a string.

```bash
iex(2)> Elixirfm.User.get_recent_tracks "polymorphic"
** (ArgumentError) cannot convert the given list to a string.
```

https://github.com/msp/cenatus-ltd/commit/7cf3855425819ecaf3633a3882d2edf726f660d8#diff-39f77ab80e68dc34a49daf6fc4480941R77

**Comment by jrichocean** [comment]
hey thanks, I just barely saw this but ill look into it now, and sorry for the late response.

**Comment by jrichocean** [comment]
hey @msp , im looking at my repo and it is working jsut fine for me. do you have your config values set?

**Comment by jrichocean** [comment]
@msp what you might be running across is when using `Elixirfm.get_request/2` the opts are a keyword list with a default of `[api_version: "2.0"]` and if  you just put the string "2.0" in the options you will get an error which is what it looks like you are doing in your code snippit. the keyword list is to be able to support other options in the future.

Let me know if that helps solve your problem, and if not I will absolutely look into it some more but i think for the time being I'm going to close this issue.

**Comment by msp** [comment]
My mistake, looks like I misread the docs. Thanks for clarifying.

**Comment by jrichocean** [comment]
np! anytime! and ill be sure to update and make the docs better as well!
