### ISSUE TITLE
Hex release of recent merge

### ISSUE THREAD

**Issue by boonious** [jrichocean/Elixirfm#5]
Hey Joshua, 

Would it be possible to release the recent merges as a new version on Hex? I would like to include Elixirfm in a published Hex software package.

Regards,

Boon

**Comment by jrichocean** [comment]
HEY! im so sorry i am seeing this so late! i will def get that done rn! and thanks for the comment!

**Comment by jrichocean** [comment]
latest update from master now published on hex.pm

**Comment by boonious** [comment]
Thanks Joshua!

I shall check the hex package out later and update `lastfm_archive` (remove stopgap codes) to include the latest of Elixirfm.
